// @mode hydrate

import * as React from "react";
import { Icons } from "./ui/Icons";
import { Button } from "./ui/Button";
import { Card, CardContent } from "./ui/Card";
import { Dialog } from "./ui/Dialog";

interface Task {
  id: string;
  title: string;
  description: string;
  priority: "low" | "medium" | "high";
  status: "todo" | "in_progress" | "done";
  createdAt: string;
}

export default function TaskBoard() {
  const [tasks, setTasks] = React.useState<Task[]>([]);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  const [title, setTitle] = React.useState("");
  const [description, setDescription] = React.useState("");
  const [priority, setPriority] = React.useState<"low" | "medium" | "high">(
    "medium",
  );

  React.useEffect(() => {
    const saved = localStorage.getItem("revelt_tasks");
    if (saved) {
      try {
        setTasks(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse tasks");
      }
    } else {
      const seed: Task[] = [
        {
          id: "1",
          title: "Explore Go & React SSR architecture",
          description:
            "Verify HTML is generated by the Go backend and hydrated on the client.",
          priority: "high",
          status: "todo",
          createdAt: new Date().toISOString(),
        },
        {
          id: "2",
          title: "Build client-side islands",
          description:
            "Develop independent React components that hydrate autonomously.",
          priority: "medium",
          status: "in_progress",
          createdAt: new Date().toISOString(),
        },
      ];
      setTasks(seed);
      localStorage.setItem("revelt_tasks", JSON.stringify(seed));
    }
  }, []);

  const saveTasks = (newTasks: Task[]) => {
    setTasks(newTasks);
    localStorage.setItem("revelt_tasks", JSON.stringify(newTasks));
  };

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    const newTask: Task = {
      id: crypto.randomUUID(),
      title,
      description,
      priority,
      status: "todo",
      createdAt: new Date().toISOString(),
    };

    const updated = [...tasks, newTask];
    saveTasks(updated);

    setTitle("");
    setDescription("");
    setPriority("medium");
    setIsModalOpen(false);
  };

  const moveTask = (id: string, dir: "next" | "prev") => {
    const updated = tasks.map((task) => {
      if (task.id !== id) return task;
      let newStatus = task.status;
      if (task.status === "todo" && dir === "next") newStatus = "in_progress";
      else if (task.status === "in_progress") {
        newStatus = dir === "next" ? "done" : "todo";
      } else if (task.status === "done" && dir === "prev")
        newStatus = "in_progress";
      return { ...task, status: newStatus };
    });
    saveTasks(updated);
  };

  const deleteTask = (id: string) => {
    const updated = tasks.filter((t) => t.id !== id);
    saveTasks(updated);
  };

  const getPriorityBadgeColor = (p: string) => {
    switch (p) {
      case "high":
        return "bg-red-50 text-red-700 border-red-200";
      case "medium":
        return "bg-amber-50 text-amber-700 border-amber-200";
      default:
        return "bg-emerald-50 text-emerald-700 border-emerald-200";
    }
  };

  const columns: {
    title: string;
    key: Task["status"];
    bg: string;
    border: string;
    text: string;
  }[] = [
    {
      title: "To Do",
      key: "todo",
      bg: "bg-slate-50/50",
      border: "border-slate-200",
      text: "text-slate-800",
    },
    {
      title: "In Progress",
      key: "in_progress",
      bg: "bg-indigo-50/20",
      border: "border-indigo-100",
      text: "text-indigo-800",
    },
    {
      title: "Done",
      key: "done",
      bg: "bg-emerald-50/20",
      border: "border-emerald-100",
      text: "text-emerald-800",
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">
            Project Workspace
          </h1>
          <p className="text-slate-500 text-sm mt-0.5 font-medium">
            Hydrated Kanban board backed by browser storage.
          </p>
        </div>
        <Button
          onClick={() => setIsModalOpen(true)}
          className="flex items-center gap-2">
          <Icons.Plus className="w-4 h-4" /> Add Task
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {columns.map((col) => (
          <div
            key={col.key}
            className={`flex flex-col rounded-xl border ${col.border} ${col.bg} p-4 min-h-112.5`}>
            <div className="flex items-center justify-between mb-4 px-1">
              <span
                className={`font-bold text-xs uppercase tracking-wider ${col.text}`}>
                {col.title}
              </span>
              <span className="bg-white border border-slate-200 text-xs px-2 py-0.5 rounded-full font-bold shadow-xs">
                {tasks.filter((t) => t.status === col.key).length}
              </span>
            </div>

            <div className="flex-1 space-y-3">
              {tasks
                .filter((task) => task.status === col.key)
                .map((task) => (
                  <Card
                    key={task.id}
                    className="hover:shadow-sm transition-shadow">
                    <CardContent className="p-4 flex flex-col gap-3">
                      <div>
                        <div className="flex items-center justify-between gap-2 mb-1.5">
                          <span
                            className={`text-[10px] font-bold tracking-wider uppercase px-2 py-0.5 rounded-md border ${getPriorityBadgeColor(task.priority)}`}>
                            {task.priority}
                          </span>
                          <button
                            onClick={() => deleteTask(task.id)}
                            className="text-slate-400 hover:text-red-500 hover:bg-red-50 p-1 rounded-md transition-all cursor-pointer">
                            <Icons.Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                        <h4 className="font-bold text-slate-900 text-sm leading-tight">
                          {task.title}
                        </h4>
                        {task.description && (
                          <p className="text-xs text-slate-500 mt-1 line-clamp-2">
                            {task.description}
                          </p>
                        )}
                      </div>

                      <div className="flex items-center justify-end gap-1.5 pt-2 border-t border-slate-100">
                        {task.status !== "todo" && (
                          <Button
                            variant="outline"
                            size="icon"
                            onClick={() => moveTask(task.id, "prev")}
                            className="h-7 w-7">
                            <Icons.ArrowLeft className="w-3.5 h-3.5" />
                          </Button>
                        )}
                        {task.status !== "done" && (
                          <Button
                            variant="outline"
                            size="icon"
                            onClick={() => moveTask(task.id, "next")}
                            className="h-7 w-7 text-indigo-600 hover:text-indigo-700">
                            <Icons.ArrowRight className="w-3.5 h-3.5" />
                          </Button>
                        )}
                        {task.status === "done" && (
                          <div className="text-emerald-600 flex items-center gap-1 text-xs font-semibold mr-1">
                            <Icons.CheckCircle2 className="w-4 h-4" /> Completed
                          </div>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              {tasks.filter((t) => t.status === col.key).length === 0 && (
                <div className="flex items-center justify-center border-2 border-dashed border-slate-200 rounded-xl h-24 text-slate-400 text-xs font-medium">
                  No tasks in this list
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      <Dialog
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Create New Task">
        <form onSubmit={handleAddTask} className="space-y-4">
          <div className="flex flex-col gap-1">
            <label className="text-xs font-bold text-slate-700">
              Task Title
            </label>
            <input
              type="text"
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., Fix build configuration"
              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-bold text-slate-700">
              Description
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Add details about this task..."
              rows={3}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-bold text-slate-700">
              Priority Level
            </label>
            <select
              value={priority}
              onChange={(e) => setPriority(e.target.value as any)}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option value="low">Low Priority</option>
              <option value="medium">Medium Priority</option>
              <option value="high">High Priority</option>
            </select>
          </div>
          <div className="flex justify-end gap-2 pt-2 border-t border-slate-100">
            <Button
              variant="outline"
              type="button"
              onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit">Create Task</Button>
          </div>
        </form>
      </Dialog>
    </div>
  );
}
